Fix kolab_alarms table schema for MariaDB (Bifrost#T163148)
Error: Specified key was too long; max key length is 767 bytes, is caused
by missing charset specification for the table. Maria's default
charset is utf8mb4 making the varchar(255) field too big for a key.